export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CONTACTS_START = 'SET_CONTACTS_START';
export const GET_CONTACTS_SUCCESS = 'SET_CONTACTS_SUCCESS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';